### PR TITLE
Added AJAX functions on filtro in R_tiempo_Departamento.php

### PR DESCRIPTION
**Pull request by Tupm3**

### CODE REVIEW

**Comment by Tupm3** [comment]
Corrected queries error on R_tiempo_Departamento.php

**Comment by ghost** [comment]
Still missing the downloadable pdf file :)

**Comment by Tupm3** [comment]
Added downloadable PDF file and onblur filter at Fecha Inicial on Table

**Comment by Tupm3** [comment]
Fixed sidebar issue

**Comment by Tupm3** [comment]
Moved PDF function to JS file

**Pull request merged**
